version: '3'

services:
  localtunnel_server:
    build: https://github.com/localtunnel/server.git
    command: --port 3000

  nginx:
    depends_on:
      - localtunnel_server
    image: defunctzombie/localtunnel-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl/
      - ./site.conf:/etc/nginx/conf.d/default.conf
