version: '3'

services:
  localtunnel_server:
    build: https://github.com/localtunnel/server.git
    command: --port 3000
    network_mode: host

  nginx:
    depends_on:
      - localtunnel_server
    image: defunctzombie/localtunnel-nginx:latest
    network_mode: host
    volumes:
      - ./ssl:/etc/nginx/ssl/
